### ISSUE TITLE
[Struts2] Unable to make a readDtList() from ContextListModifiable

### ISSUE THREAD

**Issue by forhanp** [KleeGroup/vertigo-struts2#4]
When you use a ContextListModifiable in your action and try to get the List, if there is an error into one of the object, you get the following exception :
UnsupportedOperationException : This list contains UiObject only. If objects are modifiable please use UiListModifiable instead of this one.

This is due to the findKey(DtObject) in KActionContext. When an error occurs in the objects validations, the process look through all referenced lists and not only the modifiable ones.
When you hit an unmodifiable list like a reference one published in your context, you get the error.

I see two ways to correct this :
- Remove the UnsupportedOperationException from the indexOf() in uiListUnmodifiable class
- Remove the unmodifiables list from the findKey(DtObject), there is another findKey(UiObject) that is suitable to find objects in unmodifiables lists.

**Comment by NPi2Loup** [comment]
Remove the UnsupportedOperationException from the indexOf() in uiListUnmodifiable class.
Uses super indexOf implementation.
